# Final Project Title

## Team Members

1. Ali Alperen Usta ustaa18@itu.edu.tr 090180323
2. Ezgi Özgen ozgen18@itu.edu.tr 090180344

## Dataset
Dataset Link: https://www.kaggle.com/datasets/jessicali9530/celeba-dataset

Dataset explanation was made by pulling data in the cells below. 
The data comes as a zip file. The zip file contains 4 csv files and photos in a folder. Using opendatasets library, dataset is downloaded from kaggle via api. Then, the files inside the folder were read. the following are the explanations according to the files read. This folder contains photos. Analysis will be done using photographs.

**img_align_celeba** : The folder where the photos are located. The process takes a long time because there are too many photos.

**list_attr_celeba.csv** : In this data, there are 40 different attributes related to photos. Labels change as 1 and -1. It is labeled as 1 if the relevant feature exists, -1 if it is not.

**list_bbox_celeba.csv** : Contains information about the dimensions of the photos.

**list_eval_partition.csv**: It has test-train and validation tags.

**list_landmarks_align_celeba.csv** : There are coordinates of the facial features of the people in the photos. For example, eyes, mouth, nose, etc.


## Description of the Problem

Thanks to the diversity of the dataset, many questions can be asked. During the project process, many different inferences are desired to be made. There are multiple attributes related to hair color. Therefore, a person's hair color can be predicted. One-hot-encoder can be used for labeling. In addition, estimations will be made on such different features during the project process.

hypothetically, "can the established model accurately predict the hair color of celebrities?" will answer the question

In addition, after the project is detailed, the model can be run for other attributes.

To test the correctness of the questions, some tests can be applied to the model. Some of 

1-) confusion matrix can be examined.

2-) ROC curve can be examined.

3-) The score of the model can be checked.

4-) In order to check whether the model is overfit or not, the loss function and accuracy graph can be examined on the same plot.are those;

As an algorithm, deep learning algorithms will be used, but first a basic model (logistic regression) will be established and other algorithms will be compared with this model. Since models will be tested during the project phase, the correct model determination will be made during the project.



## Project Planning


### Project Pieces

Reading and observing the data were done together. A joint meeting was held for Proposal and ideas were discussed.

**First week**:

Image processing and algorithm research: Ezgi, Ali Alperen

**Second week**:

Analyzing the data: Ali Alperen

Visualization:Ezgi

Interpretation of the results: Ezgi and Ali Alperen

**Week three and end of the project**:

Bringing the data into the appropriate format: Ali Alperen

Different Model: Ezgi Özgen

Different Model: Ali Alperen

Testing: Ezgi

Writing and editing the project: Ezgi and Ali Alperen

In [6]:
import pandas as pd
import json

f = open("C://Users//EzgiOzgen//Downloads//kaggle.json")
data = json.load(f)

In [7]:
data

{'username': 'ezgizgenn', 'key': 'af7a677401f11db4aef18e31bb2873eb'}

In [1]:
import opendatasets as od
import pandas as pd

C:\Users\EzgiOzgen\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [35]:
od.download(
    "https://www.kaggle.com/datasets/jessicali9530/celeba-dataset/download?datasetVersionNumber=2")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: torino24
Your Kaggle Key: ········

  0%|                                                                             | 1.00M/1.33G [00:00<03:30, 6.78MB/s]

Downloading celeba-dataset.zip to .\celeba-dataset

100%|█████████████████████████████████████████████████████████████████████████████| 1.33G/1.33G [01:21<00:00, 17.6MB/s]

In [36]:
file = ("C://Users//Alperen Usta//Desktop//Ders Dosyaları//388E-DataScience-Fund.Analys//celeba-dataset//list_attr_celeba.csv")

In [38]:
attr=pd.read_csv(file)

In [39]:
attr.head()

,image_id,5_o_Clock_Shadow,Arched_Eyebrows,Attractive,Bags_Under_Eyes,Bald,Bangs,Big_Lips,Big_Nose,Black_Hair,...,Sideburns,Smiling,Straight_Hair,Wavy_Hair,Wearing_Earrings,Wearing_Hat,Wearing_Lipstick,Wearing_Necklace,Wearing_Necktie,Young
0,000001.jpg,-1,1,1,-1,-1,-1,-1,-1,-1,...,-1,1,1,-1,1,-1,1,-1,-1,1
1,000002.jpg,-1,-1,-1,1,-1,-1,-1,1,-1,...,-1,1,-1,-1,-1,-1,-1,-1,-1,1
2,000003.jpg,-1,-1,-1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,1,-1,-1,-1,-1,-1,1
3,000004.jpg,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,-1,1,-1,1,-1,1,1,-1,1
4,000005.jpg,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,1

import os
from PIL import Image

os.chdir("C://Users//Alperen Usta//Desktop//Ders Dosyaları//388E-DataScience-Fund.Analys//celeba-dataset//img_align_celeba//img_align_celeba")


dirnames = os.listdir(".")

for f in dirnames:

    img = Image.open(f)
    
    display(img)

In [2]:
box=pd.read_csv(f"C://Users//EzgiOzgen//Desktop//2022-Fall-388E-main//celeba-dataset//list_bbox_celeba.csv")

In [3]:
box.head()

     image_id  x_1  y_1  width  height
0  000001.jpg   95   71    226     313
1  000002.jpg   72   94    221     306
2  000003.jpg  216   59     91     126
3  000004.jpg  622  257    564     781
4  000005.jpg  236  109    120     166

In [5]:
align=pd.read_csv(f"C://Users//EzgiOzgen//Desktop//2022-Fall-388E-main//celeba-dataset//list_landmarks_align_celeba.csv")

In [6]:
align.head()

,image_id,lefteye_x,lefteye_y,righteye_x,righteye_y,nose_x,nose_y,leftmouth_x,leftmouth_y,rightmouth_x,rightmouth_y
0,000001.jpg,69,109,106,113,77,142,73,152,108,154
1,000002.jpg,69,110,107,112,81,135,70,151,108,153
2,000003.jpg,76,112,104,106,108,128,74,156,98,158
3,000004.jpg,72,113,108,108,101,138,71,155,101,151
4,000005.jpg,66,114,112,112,86,119,71,147,104,150

In [7]:
evalpart=pd.read_csv(f"C://Users//EzgiOzgen//Desktop//2022-Fall-388E-main//celeba-dataset//list_eval_partition.csv")

In [8]:
evalpart.head()

     image_id  partition
0  000001.jpg          0
1  000002.jpg          0
2  000003.jpg          0
3  000004.jpg          0
4  000005.jpg          0